DROP TABLE IF EXISTS "tb_user" CASCADE;
DROP TABLE IF EXISTS "tb_account" CASCADE;
DROP TABLE IF EXISTS "tb_email" CASCADE;
DROP TABLE IF EXISTS "tb_dictionary" CASCADE;
DROP TABLE IF EXISTS "tb_word" CASCADE;
DROP TABLE IF EXISTS "tb_word_snapshot" CASCADE;
